package com.lpc.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;

public class SmbmsUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.id
     *
     * @mbggenerated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userCode
     *
     * @mbggenerated
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userPassword
     *
     * @mbggenerated
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.birthday
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.userRole
     *
     * @mbggenerated
     */
    private Integer userrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.createdBy
     *
     * @mbggenerated
     */
    private Integer createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.modifyBy
     *
     * @mbggenerated
     */
    private Integer modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smbms_user.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    private Integer age;

    public Integer getAge() {
        Date birthday=this.getBirthday();
        Calendar c1=Calendar.getInstance();
        c1.setTime(new Date());
        Calendar c2=Calendar.getInstance();
        c2.setTime(birthday);
        int age=c1.get(Calendar.YEAR)-c2.get(Calendar.YEAR);
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public SmbmsUser() {
    }

    public SmbmsUser(Integer id, String usercode, String username, String userpassword, Integer gender, Date birthday, String phone, String address, Integer userrole, Integer createdby, Date creationdate, Integer modifyby, Date modifydate, Integer age) {
        this.id = id;
        this.usercode = usercode;
        this.username = username;
        this.userpassword = userpassword;
        this.gender = gender;
        this.birthday = birthday;
        this.phone = phone;
        this.address = address;
        this.userrole = userrole;
        this.createdby = createdby;
        this.creationdate = creationdate;
        this.modifyby = modifyby;
        this.modifydate = modifydate;
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.id
     *
     * @return the value of smbms_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.id
     *
     * @param id the value for smbms_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userCode
     *
     * @return the value of smbms_user.userCode
     *
     * @mbggenerated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userCode
     *
     * @param usercode the value for smbms_user.userCode
     *
     * @mbggenerated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userName
     *
     * @return the value of smbms_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userName
     *
     * @param username the value for smbms_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userPassword
     *
     * @return the value of smbms_user.userPassword
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userPassword
     *
     * @param userpassword the value for smbms_user.userPassword
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.gender
     *
     * @return the value of smbms_user.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.gender
     *
     * @param gender the value for smbms_user.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.birthday
     *
     * @return the value of smbms_user.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.birthday
     *
     * @param birthday the value for smbms_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.phone
     *
     * @return the value of smbms_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.phone
     *
     * @param phone the value for smbms_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.address
     *
     * @return the value of smbms_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.address
     *
     * @param address the value for smbms_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.userRole
     *
     * @return the value of smbms_user.userRole
     *
     * @mbggenerated
     */
    public Integer getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.userRole
     *
     * @param userrole the value for smbms_user.userRole
     *
     * @mbggenerated
     */
    public void setUserrole(Integer userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.createdBy
     *
     * @return the value of smbms_user.createdBy
     *
     * @mbggenerated
     */
    public Integer getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.createdBy
     *
     * @param createdby the value for smbms_user.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.creationDate
     *
     * @return the value of smbms_user.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.creationDate
     *
     * @param creationdate the value for smbms_user.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.modifyBy
     *
     * @return the value of smbms_user.modifyBy
     *
     * @mbggenerated
     */
    public Integer getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.modifyBy
     *
     * @param modifyby the value for smbms_user.modifyBy
     *
     * @mbggenerated
     */
    public void setModifyby(Integer modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smbms_user.modifyDate
     *
     * @return the value of smbms_user.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smbms_user.modifyDate
     *
     * @param modifydate the value for smbms_user.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}